<a href="https://colab.research.google.com/github/pedroyoshikadogarcia/Aula-14-09-2026-SERS/blob/main/Aula_06_Machine_Learn_SERS_14_09_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício

Treinar um modelo preditivo de classificação binária. O modelo fara as previsões com base nos dados da coluna  'stabf' mostrando se a rede elétrica está INSTÁVEL ou ESTÁVEL. Utilizar o algoritmo Regressão Logistica (LogisticRegression do sklearn) para o treinamento do modelo. Avaliar o modelo com base na acurácia. Apresentar a Matriz de Confusão.

## Preparação do Ambiente

In [7]:
# Manipulação de Tabelas e matrizes/vetore
import pandas as pd
import numpy as np
# Gráficos
import matplotlib.pyplot as plt
import seaborn as sns
# Algoritmo de regressão logistíca
from sklearn.linear_model import LogisticRegression
# Ferramenta para separação dos dados de treino e teste
# x_train, x_test, y_train, y_test
from sklearn.model_selection import train_test_split
#Avaliação com Acurácia e matriz de confusão
from sklearn.metrics import accuracy_score, confusion_matrix

## Carregar os Dados e Criar o Dataframe

In [8]:
dados = pd.read_csv('https://raw.githubusercontent.com/pedroyoshikadogarcia/Aula-14-09-2026-SERS/refs/heads/main/Data_for_UCI_named.csv')
dados.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

## Realizar a Inspeção dos Dados

In [9]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object
dtypes: float64(13), object(1)
memory usage: 1.1+ MB

In [14]:
# Número de registros
dados.shape[0]

10000

In [11]:
# Quantas classes existem na coluna 'stabf'
dados['stabf'].unique()

array(['unstable', 'stable'], dtype=object)

In [12]:
# Quantos registros existem de cada classe na coluna 'stabf'
dados['stabf'].value_counts()

stabf
unstable    6380
stable      3620
Name: count, dtype: int64

In [10]:
# Estatisticas descritivas
# Para atributos categoricos
dados.describe(include='object')

           stabf
count      10000
unique         2
top     unstable
freq        6380